steps:
  - name: 'gcr.io/cloud-builders/go'
    env: ['GO111MODULE=on', 'PROJECT_ROOT=hello']
    args: ['mod', 'vendor']
  - name: 'gcr.io/cloud-builders/go'
    args: ['test','./cmd/grpc']
    env: ['GO111MODULE=on','PROJECT_ROOT=hello']
  - name: 'gcr.io/cloud-builders/go'
    args: ['install', './cmd/grpc/main.go']
    env: ['GO111MODULE=on', 'PROJECT_ROOT=hello']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/hello:$REVISION_ID", "."]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/hello:$REVISION_ID"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['container', 'images', 'add-tag', "gcr.io/$PROJECT_ID/hello:$REVISION_ID", "gcr.io/$PROJECT_ID/hello:latest"]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ["beta", "run", "deploy", "helloproto", "--image", "gcr.io/$PROJECT_ID/hello:$REVISION_ID", '--platform', 'managed']
